name: A Blog
author: yytcream
url: http://yytcream.github.io
baseurl: 
resume_site: http://yytcream.github.io
description: 
github_username: yytcream
github: http://github.com/yytcream
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : yytcream.github.io
    owner : yytcream
    admin : yytcream
